---

- name: apply common configuration to all nodes
  remote_user: chickenmcnoggin
  hosts: all
  
  vars_prompt:
    - name: "hostname"
      prompt: "Enter the hostname of the Raspberry Pi"
    
    - name: "password"
      prompt: "Enter password for chickenmcnoggin"
      private: yes

  roles:
    - common
  
  