---

- name: apply common configuration to all nodes
  remote_user: pi
  hosts: all
  
  vars_prompt:
        
    - name: "hostname"
      prompt: "Enter the hostname of the Raspberry Pi"
    
    - name: "password"
      prompt: "enter salted pass for chickenmcnoggin (openssl passwd -salt <salt> -1 <plaintext>)"

  roles:
    - common
  
  