---

- name: Install the package "fail2ban"
  apt:
    name: fail2ban
    state: present
  become: true

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Update all packages to the latest version
  apt:
    upgrade: dist
  become: true

- name: add new user
  user:
    name: chickenmcnoggin
    shell: /bin/bash
    groups: adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi
    append: yes
    update_password: on_create
    password: "{{password}}"
  become: true

- name: add authorized key from bash on windows
  authorized_key:
    user: chickenmcnoggin
    state: present
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
  become: true

- name: Change pi password
  user: name=pi update_password=always password= "{{crazy_pi_password}}"
