---

- name: Install the package "fail2ban"
  apt:
    name: fail2ban
    state: present

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: 'add new user'
  command: sudo useradd -m -G adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi chickenmcnoggin

#get password from input
#change password of chickenmcnoggin


- name: add authorized key from bash on windows
  authorized_key:
    user: chickenmcnoggin
    state: present
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

# Remove the user 'pi'
- user:
    name: pi
    state: absent
    remove: yes


#get and change hostname from input
#removepi user


- name: 'Reboot'
  command: sleep 2 && reboot